#pragma once

#define CUBE_ANIMATION_INTERVAL_FRAME		5
#define MAP_SCROLL_PER_FRAME				0.4
#define TARGET_CUBE_RANGE					20
#define TARGET_DEATH1_SOUND_VOLUME			45
#define TARGET_DEATH2_SOUND_VOLUME			40
#define TARGET_DEVICE_EFFECT_INTERVAL		120
#define TEEMO_EX_MODE1_HEALTH				70
#define TEEMO_EX_MODE2_HEALTH				25
#define TEEMO_EX_MODE3_HEALTH				0
#define TEEMO_MARK1_MODE1_MIN_HEALTH		45
#define TEEMO_MARK1_MODE2_MIN_HEALTH		0
#define TEEMO_MARK2_MODE1_HEALTH			55
#define TEEMO_MARK2_MODE2_HEALTH			35
#define TEEMO_MARK2_MODE3_HEALTH			0