#pragma once

#define TARGET_ATTACK_RANGE_BLUE2			4
#define TARGET_ATTACK_RANGE_BLUE3			5
#define TARGET_ATTACK_RANGE_ORANGE1			3
#define TARGET_ATTACK_RANGE_RED1			3
#define TARGET_DEVICE_EFFECT_INTERVAL		120

