#pragma once

#define CUBE_ANIMATION_INTERVAL_FRAME		5
#define MAP_SCROLL_PER_FRAME				0.4
#define TARGET_ATTACK_RANGE_BLUE1			4
#define TARGET_ATTACK_RANGE_BLUE2			4
#define TARGET_ATTACK_RANGE_BLUE3			3
#define TARGET_ATTACK_RANGE_BLUE4			2
#define TARGET_ATTACK_RANGE_BLUE7			5
#define TARGET_ATTACK_RANGE_ORANGE1			4
#define TARGET_ATTACK_RANGE_ORANGE2			4
#define TARGET_ATTACK_RANGE_ORANGE3			3
#define TARGET_ATTACK_RANGE_ORANGE5			2
#define TARGET_ATTACK_RANGE_WHITE5			2
#define TARGET_ATTACK_RANGE_RED1			3
#define TARGET_DEVICE_EFFECT_INTERVAL		120

